### ISSUE TITLE
Archivo Normas

### ISSUE THREAD

**Issue by adanbeltran** [adanbeltran/Corpus_Norms#1]
[SAMPLE-NORMS.xlsx](https://github.com/adanbeltran/Corpus_Norms/files/1709151/SAMPLE-NORMS.xlsx)

**Comment by ivmafo** [comment]
![use case diagram - atm](https://user-images.githubusercontent.com/30247/36342198-c75b7786-13c8-11e8-9283-8f4cd2cd97ff.jpg)
![screen shot 2018-02-17 at 9 16 42 am](https://user-images.githubusercontent.com/30247/36342200-dbb70ae2-13c8-11e8-99c1-100fd277a5ad.png)
![screen shot 2018-02-17 at 9 31 37 am](https://user-images.githubusercontent.com/30247/36342201-e00891a6-13c8-11e8-9b2b-3602023c7b96.png)
![screen shot 2018-02-17 at 9 32 48 am](https://user-images.githubusercontent.com/30247/36342202-e27eecc8-13c8-11e8-840b-4c70d78d12fa.png)
![screen shot 2018-02-17 at 9 33 25 am](https://user-images.githubusercontent.com/30247/36342204-e8a2cd2c-13c8-11e8-8bc6-f73c9b823205.png)
![screen shot 2018-02-17 at 9 48 25 am](https://user-images.githubusercontent.com/30247/36342206-eb0b5138-13c8-11e8-86f1-7f762dc414ed.png)
![screen shot 2018-02-17 at 9 48 33 am](https://user-images.githubusercontent.com/30247/36342207-f0078f94-13c8-11e8-9ed2-d2ea1ec734c3.png)

**Comment by ivmafo** [comment]
Diagrama entidad relacion
![modelo relacional](https://user-images.githubusercontent.com/30247/36342249-5eee4844-13c9-11e8-83b7-09f7b92501be.jpg)
